module-title = "Google Cloud Datastore"

input-descriptor-file = "descriptor.pb"

output-dir = "output"

footer-content = "© 2023 Mark Vincze. All rights reserved."

repository-url = "https://github.com/googleapis/googleapis"
repository-type = "github"
repository-branch = "main"

