version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          app-dir: ~/project/src/sabledocs/
      - run:
          command: |
            pip install build
            python -m build -C--global-option=egg_info -C--global-option=--tag-build="dev${CIRCLE_BUILD_NUM}"
      - persist_to_workspace:
          root: dist
          paths:
            - "*"
  publish_testpypi:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - attach_workspace:
          at: dist
      - run:
          command: |
            pip install twine
            python -m twine upload -u __token__ -p ${PYPI_API_TOKEN_TEST} --repository testpypi ~/project/dist/*
  publish_pypi:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - attach_workspace:
          at: dist
      - run:
          command: |
            pip install twine
            python -m twine upload -u __token__ -p ${PYPI_API_TOKEN} ~/project/dist/*
workflows:
  build-and-publish:
    jobs:
      - build
      - publish_testpypi:
          requires:
            - build
      - publish_pypi:
          requires:
            - build
          filters:
            branches:
              only:
                - main
