version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build_dev:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          app-dir: ~/project/src/sabledocs/
      - run:
          command: |
            pip install build
            python -m build -C--global-option=egg_info -C--global-option=--tag-build=".${CIRCLE_BUILD_NUM}dev"
      - persist_to_workspace:
          root: dist
          paths:
            - "*"

  build_stable:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          app-dir: ~/project/src/sabledocs/
      - run:
          command: |
            pip install build
            python -m build -C--global-option=egg_info -C--global-option=--tag-build=".${CIRCLE_BUILD_NUM}"
      - persist_to_workspace:
          root: dist
          paths:
            - "*"

  publish_pypi:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - attach_workspace:
          at: dist
      - run:
          command: |
            pip install twine
            python -m twine upload -u __token__ -p ${PYPI_API_TOKEN} ~/project/dist/*

  generate_sample_docs:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          app-dir: ~/project/src/sabledocs/
      - run:
          command: |
            chmod +x generate_sample_docs.sh
            ./generate_sample_docs.sh

workflows:
  build-and-publish:
    jobs:
      - build_dev:
          filters:
            branches:
              ignore:
                - main
      - build_stable:
          filters:
            branches:
              only:
                - main
      - publish_pypi:
          name: publish_pypi_dev
          requires:
            - build_dev
      - publish_pypi:
          name: publish_pypi_stable
          requires:
            - build_stable
      - generate_sample_docs:
          requires:
            - publish_pypi_stable
