module-title = "Google Cloud Pub/Sub"

input-descriptor-file = "pubsub.pb"

output-dir = "output"

footer-content = "© Example 2023"

repository-url = "https://github.com/googleapis/googleapis"
repository-type = "github"
repository-branch = "master"
