module-title = "Google Cloud SDK"

input-descriptor-file = "google-cloud-sdk.pb"

output-dir = "output"

footer-content = "© Example 2023"

repository-url = "https://github.com/googleapis/googleapis"
repository-type = "github"
repository-branch = "master"
